behaviors:
  Mover:
    trainer_type: ppo
    hyperparameters:
      batch_size: 6000
      buffer_size: 30000
      learning_rate: 0.00002
      beta: 0.001
      epsilon: 0.05
      lambd: 0.9975
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 15000000
    time_horizon: 2500
    summary_freq: 30000
  Targetter:
    trainer_type: ppo
    hyperparameters:
      batch_size: 6000
      buffer_size: 24000
      learning_rate: 0.0005
      beta: 0.001
      epsilon: 0.2
      lambd: 0.995
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 1024
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.55
        strength: 1.0
    keep_checkpoints: 15
    max_steps: 15000000
    time_horizon: 1000
    summary_freq: 30000