behaviors:
  Mover:
    trainer_type: ppo
    hyperparameters:
      batch_size: 6000
      buffer_size: 30000
      learning_rate: 0.0002
      beta: 0.001
      epsilon: 0.05
      lambd: 0.9975
      num_epoch: 8
      learning_rate_schedule: constant
      shared_critic: true
    network_settings:
      normalize: false
      hidden_units: 1024
      num_layers: 8
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 15000000
    time_horizon: 3000
    summary_freq: 30000